### ISSUE TITLE
Pong agents don't play well

### ISSUE THREAD

**Issue by joshua-matt** [psuwuxian/rl_attack#10]
When I run `plot.py` on the supplied adversary model (see below image), it looks like it learns to play pretty well. However, when I watch it play by running `test_agent.py` (with `want_test_window=True`), neither player is very responsive. In particular, their behavior is much different from that shown in [this video](https://www.youtube.com/watch?v=-_j-fmVpn_s&t=2221s).

The purple adversary, by default, slides down to the bottom right corner of its box, and only moves away when it's already too late to hit the ball. It shows some knowledge of how to play, since it moves forward to hit the ball when it's close to the bottom right. The blue victim stays more in the center, but seems to move at random. 

This issue happens in the unedited version of this repo. Any idea what's going on?

![image](https://user-images.githubusercontent.com/29611603/125329240-e240ae80-e30a-11eb-846c-3c269ac87a9a.png)

**Comment by psuwuxian** [comment]
I don't enable this function in this repo, you could write your own playing function based on the test_agent.py.

**Comment by nuwuxian** [comment]
Thanks for your attention, I don't enable the test function to show the demo videos in this repo. The test_agent.py is only a demonstration. You could write your own test function based on it. Besides, the demo videos I show in the paper are against a different victim agent. I will enable this function sooner. If you watch the demo video carefully, you will notice that at the most time the pong is bounded between the boundary of the environment without touching the left/right paddle. To make a better illustration, I cut the video to show the interaction between the pong and paddle.

**Comment by nuwuxian** [comment]
Since the victim agents are trained by self-play, they may don't perform very well. Even though Adversarial trained agents could beat these victims with a ratio of 90% winning rate, it does not mean these adversarially trained agents are very responsive. It just means it could attack the victim agent (well trained or not).  For more examples, I encourage you to see the behavior of the adversarial agents in MujoCo demo videos.  The purpose of our paper is not to train a more powerful agent which behaves like a normal agent , rather we want to train an adversarial agent that could attack the victim agent.
